version: '3.8'

services:
  backend:
    build: ./backend
    container_name: go-healthchecker-backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: go-healthchecker-frontend
    ports:
      - "4200:80"
    restart: unless-stopped
    depends_on:
      - backend
